apiVersion: v1
kind: ConfigMap
metadata:
  name: sablier-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: sablier-{{ .Release.Name }}
data:
  sablier.yml: |
    {{- $defaults := dict "logging" (dict "level" .Values.logLevel) }}
    {{- $config := mergeOverwrite $defaults (deepCopy (.Values.config | default dict)) }}
    {{- toYaml $config | nindent 4 }}
